language: objective-c
osx_image: xcode10
xcode_project: Elapse.xcodeproj # path to your xcodeproj folder
xcode_scheme: ElapseTests
xcode_sdk: iphonesimulator

script:
   - pod lib lint --allow-warnings
   - xcodebuild clean test -scheme Elapse_macOS -configuration Debug -destination 'platform=OS X'
   - xcodebuild clean test -scheme Elapse_iOS -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.0'
   - xcodebuild clean test -scheme Elapse_tvOS -configuration Debug -destination 'platform=tvOS Simulator,name=Apple TV 4K,OS=12.0'
